Repository googollee/go-socket.io, pull requests merged in 2021-05, with the labels that each got.

#448 fix: typo
  conn.go
  errors.go
  namespace_conn.go
  namespace_handler.go
  redis_broadcast.go
Labels: enhancement

#449 ref: engineio base
  .gitignore
  engineio/.gitignore
  engineio/.travis.yml
  engineio/Makefile
  engineio/base/conn.go
  engineio/base/conn_test.go
  engineio/base/errors.go
  engineio/base/frame.go
  engineio/base/packet_test.go
  engineio/base/util_test.go
  engineio/gosweep.sh
Labels: enhancement

#457 add: golangci output message format
  .golangci.yml
Labels: enhancement

#461 add: cover option in makefile
  Makefile
Labels: documentation, enhancement

#465 add: old golang version in pipeline
  .github/workflows/unittest.yaml
Labels: enhancement

#469 chore: change port by unification at examples
  _examples/gf/main.go
  _examples/gin-cors/main.go
  _examples/gin-gonic/main.go
  _examples/go-echo/main.go
  _examples/redis-adapter/main.go
Labels: documentation

#470 add: Docker example
  _examples/dockerize-default-http/.dockerignore
  _examples/dockerize-default-http/Dockerfile
  _examples/dockerize-default-http/Makefile
  _examples/dockerize-default-http/README.md
  _examples/dockerize-default-http/asset/index.html
  _examples/dockerize-default-http/go.mod
  _examples/dockerize-default-http/go.sum
  _examples/dockerize-default-http/main.go
Labels: documentation, example

#473 ref: examples
  _examples/asset/index.html
  _examples/default-http/go.mod
  _examples/default-http/main.go
  _examples/dockerize-default-http/go.mod
  _examples/dockerize-default-http/main.go
  _examples/gf/go.mod
  _examples/gf/main.go
  _examples/gin-cors/go.mod
  _examples/gin-cors/main.go
  _examples/gin-gonic/go.mod
  _examples/gin-gonic/main.go
  _examples/go-echo/go.mod
  _examples/iris/go.mod
  _examples/iris/main.go
  _examples/redis-adapter/go.mod
  _examples/redis-adapter/main.go
Labels: documentation, examples

#474 add: graceful-shutdown
  _examples/graceful-shutdown/go.mod
  _examples/graceful-shutdown/go.sum
  _examples/graceful-shutdown/main.go
Labels: documentation, examples

#475 add: fix lint
  .golangci.yml
  engineio/payload/decoder_test.go
  engineio/payload/encoder_test.go
  engineio/payload/errors.go
  engineio/payload/payload.go
  engineio/payload/payload_test.go
  engineio/payload/util_test.go
  engineio/transport/websocket/wrapper.go
  redis_broadcast.go
Labels: enhancement

#477 add: cors allowed into default http example
  _examples/default-http/main.go
Labels: documentation, examples, might-be-cors-issue

#464 add: unix socket for redis_broadcast.go
  _examples/redis-adapter/docker-compose.yml
  adapter_options.go
  redis_broadcast.go
  server.go
Labels: enhancement, v1.4

#471 Transport design v3.
  engine/transport/factory.go
  engine/transport/protocol.go
Labels: engineio, new-feature, v4

#478 add: pprof http example
  _examples/pprof/go.mod
  _examples/pprof/go.sum
  _examples/pprof/main.go
  engineio/payload/errors_test.go
Labels: documentation, examples

#462 Refactor server option
  engineio/_examples/main.go
  engineio/server.go
  engineio/server_options.go
  engineio/server_test.go
Labels: v2

#483 ref: change transport file names
  engineio/transport/manager.go
  engineio/transport/manager_test.go
  engineio/transport/parameters.go
  engineio/transport/parameters_test.go
Labels: enhancement, v1.4
